mod 'module_data',  '0.0.1',  :github_tarball => 'ripienaar/puppet-module-data'
mod 'boxen',        '3.4.0', :github_tarball => 'boxen/puppet-boxen'
mod 'homebrew',     '1.9.5', :github_tarball => 'boxen/puppet-homebrew'
mod 'stdlib',       '4.2.1',  :github_tarball => 'puppetlabs/puppetlabs-stdlib'
