mod 'module_data',  '0.0.3',  :github_tarball => 'ripienaar/puppet-module-data'
mod 'boxen',        '3.10.1', :github_tarball => 'boxen/puppet-boxen'
mod 'homebrew',     '1.11.2', :github_tarball => 'boxen/puppet-homebrew'
mod 'stdlib',       '4.2.1',  :github_tarball => 'puppetlabs/puppetlabs-stdlib'
